### PR TITLE
fix null exception when loading settings

### PR DESCRIPTION
**Pull request by rYuuk**
## Description

Fixed null exception when loading instance of settings through settings asset.

## How to Test

Verify if there is no null exception while opening settings window

### CODE REVIEW

**Review by HarrisonHough — APPROVED** [review]
It works for most purposes, however for Unity-SDK project it would crash/breack if we tried to build with WebView because WebViewPanel will try to load from resources to get the subdomain 
image

**Comment by srcnalt** [comment]
Shall we make things so that building from Unity-SDK works? I always import into a project and build to go tru user experience.

**Comment by HarrisonHough** [comment]
> Shall we make things so that building from Unity-SDK works? I always import into a project and build to go tru user experience.

an easy workaround is to just create a RPM settings object inside Unity-SDK/Assets/Resources/.....

**Comment by srcnalt** [comment]
> > Shall we make things so that building from Unity-SDK works? I always import into a project and build to go tru user experience.
> 
> an easy workaround is to just create a RPM settings object inside Unity-SDK/Assets/Resources/Settings.....

Yes tbh,m getting from same source just makes sense to me, both for settings and configs, I'd rather have them in a resources folder in Unity-SDK as well

**Review by srcnalt — APPROVED** [review]

**Pull request merged**
